# Generated by Django 4.2.6 on 2025-01-10 00:38

from django.db import migrations, models
import email_log.models


class Migration(migrations.Migration):

    dependencies = [
        ("email_log", "0004_alter_attachment_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="file",
            field=models.FileField(
                max_length=200,
                upload_to=email_log.models.get_attachment_path,
                verbose_name="file",
            ),
        ),
    ]
